<option
value="AF" >Afeganistão [AF]</option><option
value="AL" >Albânia [AL]</option><option
value="DE" >Alemanha [DE]</option><option
value="AD" >Andorra [AD]</option><option
value="AO"  selected="selected" >Angola [AO]</option><option
value="AI" >Anguilha [AI]</option><option
value="AQ" >Antárctica [AQ]</option><option
value="AN" >Antilhas Holandesas [AN]</option><option
value="AG" >Antígua e Barbuda [AG]</option><option
value="SA" >Arábia Saudita [SA]</option><option
value="AR" >Argentina [AR]</option><option
value="DZ" >Argélia [DZ]</option><option
value="AM" >Arménia [AM]</option><option
value="AW" >Aruba [AW]</option><option
value="AU" >Austrália [AU]</option><option
value="AZ" >Azerbeijão [AZ]</option><option
value="ZA" >África do Sul [ZA]</option><option
value="AT" >Áustria [AT]</option><option
value="BS" >Baamas [BS]</option><option
value="BH" >Bahrein [BH]</option><option
value="BD" >Bangladeche [BD]</option><option
value="BB" >Barbados [BB]</option><option
value="BZ" >Belize [BZ]</option><option
value="BJ" >Benim [BJ]</option><option
value="BM" >Bermudas [BM]</option><option
value="BE" >Bélgica [BE]</option><option
value="BY" >Bielorrússia [BY]</option><option
value="BO" >Bolívia [BO]</option><option
value="BW" >Botswana [BW]</option><option
value="BA" >Bósnia-Herzegovina [BA]</option><option
value="BR" >Brasil [BR]</option><option
value="BN" >Brunei [BN]</option><option
value="BG" >Bulgária [BG]</option><option
value="BF" >Burkina-Faso [BF]</option><option
value="BI" >Burundi [BI]</option><option
value="BT" >Butão [BT]</option><option
value="CV" >Cabo Verde [CV]</option><option
value="KH" >Camboja [KH]</option><option
value="CA" >Canadá [CA]</option><option
value="KZ" >Cazaquistão [KZ]</option><option
value="TD" >Chade [TD]</option><option
value="CL" >Chile [CL]</option><option
value="CN" >China [CN]</option><option
value="CY" >Chipre [CY]</option><option
value="CO" >Colômbia [CO]</option><option
value="KM" >Comores [KM]</option><option
value="CG" >Congo-Brazzaville [CG]</option><option
value="KP" >Coreia do Norte [KP]</option><option
value="KR" >Coreia do Sul [KR]</option><option
value="CR" >Costa Rica [CR]</option><option
value="CI" >Costa do Marfim [CI]</option><option
value="HR" >Croácia [HR]</option><option
value="KW" >Cuaite [KW]</option><option
value="CU" >Cuba [CU]</option><option
value="DK" >Dinamarca [DK]</option><option
value="DJ" >Djibuti [DJ]</option><option
value="DM" >Dominica [DM]</option><option
value="EG" >Egipto [EG]</option><option
value="SV" >El Salvador [SV]</option><option
value="AE" >Emiratos Árabes Unidos [AE]</option><option
value="EC" >Equador [EC]</option><option
value="ER" >Eritreia [ER]</option><option
value="SK" >Eslováquia [SK]</option><option
value="SI" >Eslovénia [SI]</option><option
value="ES" >Espanha [ES]</option><option
value="FM" >Estados Federados da Micronésia [FM]</option><option
value="US" >Estados Unidos [US]</option><option
value="EE" >Estónia [EE]</option><option
value="SJ" >Esvalbarda e Jan Mayen [SJ]</option><option
value="ET" >Etiópia [ET]</option><option
value="FJ" >Fiji [FJ]</option><option
value="PH" >Filipinas [PH]</option><option
value="FI" >Finlândia [FI]</option><option
value="FR" >França [FR]</option><option
value="GA" >Gabão [GA]</option><option
value="GH" >Gana [GH]</option><option
value="GM" >Gâmbia [GM]</option><option
value="GE" >Geórgia [GE]</option><option
value="GS" >Geórgia do Sul e Ilhas Sandwich do Sul [GS]</option><option
value="GG" >Gernsey [GG]</option><option
value="GI" >Gibraltar [GI]</option><option
value="GD" >Granada [GD]</option><option
value="GR" >Grécia [GR]</option><option
value="GL" >Gronelândia [GL]</option><option
value="GP" >Guadalupe [GP]</option><option
value="GU" >Guam [GU]</option><option
value="GT" >Guatemala [GT]</option><option
value="GF" >Guiana Francesa [GF]</option><option
value="GY" >Guiana [GY]</option><option
value="GQ" >Guiné Equatorial [GQ]</option><option
value="GN" >Guiné [GN]</option><option
value="GW" >Guiné-Bissau [GW]</option><option
value="HT" >Haiti [HT]</option><option
value="HN" >Honduras [HN]</option><option
value="HK" >Hong Kong - Região Administrativa Especial da China [HK]</option><option
value="HU" >Hungria [HU]</option><option
value="YE" >Iémen [YE]</option><option
value="BV" >Ilha Bouvet [BV]</option><option
value="HM" >Ilha Heard e Ilhas McDonald [HM]</option><option
value="NF" >Ilha Norfolque [NF]</option><option
value="IM" >Ilha de Man [IM]</option><option
value="CX" >Ilha do Natal [CX]</option><option
value="AX" >Ilhas Alanda [AX]</option><option
value="KY" >Ilhas Caimão [KY]</option><option
value="CC" >Ilhas Cocos [CC]</option><option
value="CK" >Ilhas Cook [CK]</option><option
value="FK" >Ilhas Falkland ou Malvinas [FK]</option><option
value="FO" >Ilhas Faroé [FO]</option><option
value="MP" >Ilhas Mariana do Norte [MP]</option><option
value="MH" >Ilhas Marshall [MH]</option><option
value="UM" >Ilhas Minor Outlying (E.U.A) [UM]</option><option
value="SB" >Ilhas Salomão [SB]</option><option
value="TC" >Ilhas Turcas e Caicos [TC]</option><option
value="VG" >Ilhas Virgens Britânicas [VG]</option><option
value="VI" >Ilhas Virgin E.U.A. [VI]</option><option
value="ID" >Indonésia [ID]</option><option
value="IQ" >Iraque [IQ]</option><option
value="IR" >Irão [IR]</option><option
value="IE" >Irlanda [IE]</option><option
value="IS" >Islândia [IS]</option><option
value="IL" >Israel [IL]</option><option
value="IT" >Itália [IT]</option><option
value="IN" >Índia [IN]</option><option
value="JM" >Jamaica [JM]</option><option
value="JP" >Japão [JP]</option><option
value="JE" >Jersey [JE]</option><option
value="JO" >Jordânia [JO]</option><option
value="XK" >Kosovo [XK]</option><option
value="LA" >Laos, República Popular Democrática do [LA]</option><option
value="LS" >Lesoto [LS]</option><option
value="LV" >Letónia [LV]</option><option
value="LR" >Libéria [LR]</option><option
value="LI" >Liechtenstein [LI]</option><option
value="LT" >Lituânia [LT]</option><option
value="LB" >Líbano [LB]</option><option
value="LY" >Líbia [LY]</option><option
value="LU" >Luxemburgo [LU]</option><option
value="MO" >Macau - Região Administrativa Especial da China [MO]</option><option
value="MK" >Macedónia, República da [MK]</option><option
value="MG" >Madagáscar [MG]</option><option
value="MW" >Malaui [MW]</option><option
value="MY" >Malásia [MY]</option><option
value="MV" >Maldivas [MV]</option><option
value="ML" >Mali [ML]</option><option
value="MT" >Malta [MT]</option><option
value="MA" >Marrocos [MA]</option><option
value="MQ" >Martinica [MQ]</option><option
value="MR" >Mauritânia [MR]</option><option
value="MU" >Maurícias [MU]</option><option
value="YT" >Mayotte [YT]</option><option
value="MX" >México [MX]</option><option
value="MM" >Mianmar [MM]</option><option
value="MZ" >Moçambique [MZ]</option><option
value="MD" >Moldávia, República da [MD]</option><option
value="MN" >Mongólia [MN]</option><option
value="MS" >Monserrate [MS]</option><option
value="ME" >Montenegro [ME]</option><option
value="MC" >Mónaco [MC]</option><option
value="NA" >Namíbia [NA]</option><option
value="NR" >Nauru [NR]</option><option
value="NP" >Nepal [NP]</option><option
value="NI" >Nicarágua [NI]</option><option
value="NG" >Nigéria [NG]</option><option
value="NU" >Niue [NU]</option><option
value="NE" >Níger [NE]</option><option
value="NO" >Noruega [NO]</option><option
value="NC" >Nova Caledónia [NC]</option><option
value="NZ" >Nova Zelândia [NZ]</option><option
value="OM" >Omã [OM]</option><option
value="NL" >Países Baixos [NL]</option><option
value="PW" >Palau [PW]</option><option
value="PA" >Panamá [PA]</option><option
value="PG" >Papua Nova Guiné [PG]</option><option
value="PK" >Paquistão [PK]</option><option
value="PY" >Paraguai [PY]</option><option
value="PE" >Peru [PE]</option><option
value="PN" >Pitcairn [PN]</option><option
value="PF" >Polinésia Francesa [PF]</option><option
value="PL" >Polónia [PL]</option><option
value="PR" >Porto Rico [PR]</option><option
value="PT" >Portugal [PT]</option><option
value="QA" >Qatar [QA]</option><option
value="KE" >Quénia [KE]</option><option
value="KG" >Quirguizistão [KG]</option><option
value="KI" >Quiribati [KI]</option><option
value="GB" >Reino Unido [GB]</option><option
value="CF" >República Centro-Africana [CF]</option><option
value="CZ" >República Checa [CZ]</option><option
value="CD" >República Democrática do Congo [CD]</option><option
value="DO" >República Dominicana [DO]</option><option
value="CM" >República dos Camarões [CM]</option><option
value="RE" >Reunião [RE]</option><option
value="RO" >Roménia [RO]</option><option
value="RW" >Ruanda [RW]</option><option
value="RU" >Rússia [RU]</option><option
value="KN" >Saint Kitts e Nevis [KN]</option><option
value="PM" >Saint Pierre e Miquelon [PM]</option><option
value="AS" >Samoa Americana [AS]</option><option
value="WS" >Samoa [WS]</option><option
value="SH" >Santa Helena [SH]</option><option
value="LC" >Santa Lúcia [LC]</option><option
value="EH" >Sara Ocidental [EH]</option><option
value="BL" >São Bartolomeu [BL]</option><option
value="SM" >São Marino [SM]</option><option
value="MF" >São Martinho [MF]</option><option
value="ST" >São Tomé e Príncipe [ST]</option><option
value="VC" >São Vicente e Granadinas [VC]</option><option
value="SC" >Seicheles [SC]</option><option
value="SN" >Senegal [SN]</option><option
value="SL" >Serra Leoa [SL]</option><option
value="RS" >Sérvia [RS]</option><option
value="CS" >Sérvia e Montenegro [CS]</option><option
value="SG" >Singapura [SG]</option><option
value="SY" >Síria [SY]</option><option
value="SO" >Somália [SO]</option><option
value="LK" >Sri Lanka [LK]</option><option
value="SZ" >Suazilândia [SZ]</option><option
value="SD" >Sudão [SD]</option><option
value="SE" >Suécia [SE]</option><option
value="CH" >Suíça [CH]</option><option
value="SR" >Suriname [SR]</option><option
value="TH" >Tailândia [TH]</option><option
value="TW" >Taiwan [TW]</option><option
value="TJ" >Tajiquistão [TJ]</option><option
value="TZ" >Tanzânia [TZ]</option><option
value="IO" >Território Britânico do Oceano Índico [IO]</option><option
value="PS" >Território Palestiniano [PS]</option><option
value="TF" >Territórios Franceses do Sul [TF]</option><option
value="TL" >Timor Leste [TL]</option><option
value="TG" >Togo [TG]</option><option
value="TO" >Tonga [TO]</option><option
value="TK" >Toquelau [TK]</option><option
value="TT" >Trindade e Tobago [TT]</option><option
value="TN" >Tunísia [TN]</option><option
value="TM" >Turquemenistão [TM]</option><option
value="TR" >Turquia [TR]</option><option
value="TV" >Tuvalu [TV]</option><option
value="UA" >Ucrânia [UA]</option><option
value="UG" >Uganda [UG]</option><option
value="QU" >União Europeia [QU]</option><option
value="UY" >Uruguai [UY]</option><option
value="UZ" >Usbequistão [UZ]</option><option
value="VU" >Vanuatu [VU]</option><option
value="VA" >Vaticano [VA]</option><option
value="VE" >Venezuela [VE]</option><option
value="VN" >Vietname [VN]</option><option
value="WF" >Wallis e Futuna [WF]</option><option
value="ZM" >Zâmbia [ZM]</option><option
value="ZW" >Zimbabwe [ZW]</option>